{{- $longhornSC := (lookup "storage.k8s.io/v1" "StorageClass" "" "longhorn") -}}
{{- if not $longhornSC }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .Values.persistence.defaultClass | quote }}
  labels: {{- include "longhorn.labels" . | nindent 4 }}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: "{{ .Values.persistence.reclaimPolicy }}"
parameters:
  numberOfReplicas: "{{ .Values.persistence.defaultClassReplicaCount }}"
  staleReplicaTimeout: "30"
  fromBackup: ""
  baseImage: ""
  {{- if .Values.recurringJobs.enable }}
  recurringJobs: '{{ .Values.recurringJobs.jobsList | toPrettyJson | indent 2 | trim }}'
  {{- end }}
{{- else if eq $longhornSC.provisioner "driver.longhorn.io"}}
{{ $longhornSC | mustToPrettyJson }}
{{- else}}
{{- fail "the existing longhorn storageclass doesn't have provisioner as driver.longhorn.io" }}
{{- end}}
